// <auto-generated />
using EADS.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EADS.Infrastructure.Migrations
{
    [DbContext(typeof(EADSContext))]
    partial class EADSContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("EADS.Domain.Models.Entities.DemoPresentationEncObject", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptionValueId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EncryptionValueId");

                    b.ToTable("DemoPresentationEncObjects");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.EncryptionValue", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InitVector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KeySize")
                        .HasColumnType("int");

                    b.Property<int>("PassIterations")
                        .HasColumnType("int");

                    b.Property<string>("SaltValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EncryptionValues");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.EncStringData", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptionValueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("EncryptionValueId");

                    b.ToTable("EncStringData");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.TestEncObject", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptionValueId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EncryptionValueId");

                    b.ToTable("EncObjectData");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.DemoPresentationEncObject", b =>
                {
                    b.HasOne("EADS.Domain.Models.Entities.EncryptionValue", "EncryptionValue")
                        .WithMany()
                        .HasForeignKey("EncryptionValueId");

                    b.Navigation("EncryptionValue");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.EncStringData", b =>
                {
                    b.HasOne("EADS.Domain.Models.Entities.EncryptionValue", "EncryptionValue")
                        .WithMany()
                        .HasForeignKey("EncryptionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncryptionValue");
                });

            modelBuilder.Entity("EADS.Domain.Models.Entities.TestEncObject", b =>
                {
                    b.HasOne("EADS.Domain.Models.Entities.EncryptionValue", "EncryptionValue")
                        .WithMany()
                        .HasForeignKey("EncryptionValueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EncryptionValue");
                });
#pragma warning restore 612, 618
        }
    }
}
